theme: jekyll-theme-architect
permalink: /:year/:i_month/:i_day/:title.html
exclude: [Rakefile, Gemfile, Gemfile.lock, README.md, Capfile, bin, s3_website.yml, tmp]
paginate: 3
# About/contact
author:
  name: Ifunga Ndana
  description: I am an experienced Software Developer who puts a strong emphasis on quality. I'm always interested in challenging projects and learning new skills. I am looking for positions where my technical experience, project management and leadership abilities can take a product from conception to reality. I am a highly skilled IT professional whose goal is to contribute immensely to overall company productivity and corporate image..
  contact:
    linkedin:  http://www.linkedin.com/pub/ifunga-ndana/44/a30/667
    github:    https://github.com/SubiyaCryolite
    # facebook:  <hide>
    twitter:   https://twitter.com/SubiyaCryolite
    email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Github Project:
    - 'http://subiyacryolite.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

google_analytics_token: UA-24270377-1
google_analytics: UA-24270377-1
disqus_short_name: 'thescndgenesisofficialsite'