theme: jekyll-theme-architect
permalink: /:year/:i_month/:i_day/:title.html
exclude: [README.md]
paginate: 3
# About/contact
author:
  name: Ifunga Ndana
  description: I am an experienced Software Developer who puts a strong emphasis on quality. I'm always interested in challenging projects and learning new skills. I am looking for positions where my technical experience, project management and leadership abilities can take a product from conception to reality. I am a highly skilled IT professional whose goal is to contribute immensely to overall company productivity and corporate image..
  contact:
    linkedin:  http://www.linkedin.com/pub/ifunga-ndana/44/a30/667
    github:    https://github.com/SubiyaCryolite
    twitter:   https://twitter.com/SubiyaCryolite

google_analytics_token: UA-24270377-2
google_analytics: UA-24270377-2
disqus_short_name: 'thescndgenesisofficialsite'