theme: jekyll-theme-architect
permalink: /:year/:i_month/:i_day/:title.html
google_analytics: UA-24270377-1
exclude: [Rakefile, Gemfile, Gemfile.lock, README.md, Capfile, bin, s3_website.yml, tmp]
paginate: 3